### ISSUE TITLE
Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by vczb** [mr3saru/telegram-contact-form#4]
![image](https://user-images.githubusercontent.com/51221635/156897025-de1fa43a-660e-40b4-8579-6c9f270f453b.png)

when you send a request from `'/api/form'` this log are happening on the terminal

```bash
Unhandled rejection Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (/home/vini/code/mrsaru/telegram-contact-form/node_modules/express/lib/response.js:776:10)
    at ServerResponse.contentType (/home/vini/code/mrsaru/telegram-contact-form/node_modules/express/lib/response.js:604:15)
    at ServerResponse.sendStatus (/home/vini/code/mrsaru/telegram-contact-form/node_modules/express/lib/response.js:362:8)
    at /home/vini/code/mrsaru/telegram-contact-form/index.js:38:11
    at tryCatcher (/home/vini/code/mrsaru/telegram-contact-form/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/vini/code/mrsaru/telegram-contact-form/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/vini/code/mrsaru/telegram-contact-form/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/vini/code/mrsaru/telegram-contact-form/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/vini/code/mrsaru/telegram-contact-form/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/vini/code/mrsaru/telegram-contact-form/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/vini/code/mrsaru/telegram-contact-form/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/vini/code/mrsaru/telegram-contact-form/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/vini/code/mrsaru/telegram-contact-form/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21)
```

**Comment by laurittab** [comment]
Hi Vinicius

Feel free to assign me this one as well. I came across this error when I was testing the responses. Just needs a simple change like:

_res.status(200).send('sucess')_

**Comment by laurittab** [comment]
Thanks, I'll make a start in it tomorrow.

**Comment by vczb** [comment]
> Thanks, I'll make a start in it tomorrow.

you are welcome :)
